# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1608, 854)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 1611, 821))
        font = QtGui.QFont()
        font.setFamily("Dutch801 XBd BT")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        # Load GIF using QMovie
        gif_path = "gif_path = "C:/Path/To/assets/interface.gif"
f"
        try:
            if not QtCore.QFile.exists(gif_path):
                print(f"Error: GIF file not found at {gif_path}")
            else:
                self.movie = QtGui.QMovie(gif_path)
                if not self.movie.isValid():
                    print(f"Error: Invalid GIF file at {gif_path}")
                else:
                    self.label.setMovie(self.movie)
                    self.movie.start()
                    print(f"Successfully loaded GIF: {gif_path}")
        except Exception as e:
            print(f"Error loading GIF: {e}")

        self.Activate = QtWidgets.QPushButton(self.centralwidget)
        self.Activate.setGeometry(QtCore.QRect(510, 617, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Activate.setFont(font)
        self.Activate.setStyleSheet("color: rgb(44, 223, 202);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.Activate.setObjectName("Activate")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 730, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 222, 222);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 280, 141, 31))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(70, 360, 151, 31))
        self.textBrowser_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(70, 200, 141, 31))
        self.textBrowser_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(50, 460, 181, 31))
        self.textBrowser_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(50, 570, 181, 31))
        self.textBrowser_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(60, 670, 161, 21))
        self.textBrowser_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(1340, 70, 256, 111))
        self.textBrowser_8.setStyleSheet(
            "background-color: rgba(0, 0, 0, 0.5);\n"
            "color: rgb(0, 255, 255);\n"
            "font-family: 'Segoe UI';\n"
            "font-size: 14pt;\n"
            "border: 1px solid rgba(255, 255, 255, 0.2);\n"
            "border-radius: 5px;\n"
            "padding: 5px;"
        )
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(1350, 240, 241, 91))
        self.textBrowser_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(1340, 450, 256, 111))
        self.textBrowser_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-radius: none")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 350, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(0, 220, 220);")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        JarvisUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JarvisUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1608, 26))
        self.menubar.setObjectName("menubar")
        JarvisUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JarvisUi)
        self.statusbar.setObjectName("statusbar")
        JarvisUi.setStatusBar(self.statusbar)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.Activate.setText(_translate("JarvisUi", "Activate"))
        self.pushButton.setText(_translate("JarvisUi", "Terminate"))
        self.label_2.setText(_translate("JarvisUi", "J.A.R.V.I.S"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
